#ifndef ENUMS_H_
#define ENUMS_H_

typedef enum transport_get_from_state {
	TRANSPORT_GET_FROM_BYTE_PHISICAL,
	TRANSPORT_GET_FROM_BYTE_GENERATOR,
	TRANSPORT_GET_FROM_PACKET_PHISICAL,
	DEFAULT
} TRANSPORT_GET_FROM_STATE;

typedef enum application_byte_gen_state {
	APPLICATION_GET_FROM_BYTE_PHYSICAL,
	APPLICATION_GET_FROM_PACKET_PHYSICAL,
	APPLICATION_SEND_TO_BYTE_PHYSICAL,
	APPLICATION_SEND_TO_PACKET_PHYSICAL
} APPLICATION_BYTE_GEN_STATE;

typedef enum physical_state {
	PHYSICAL_SEND_TO_BYTE_PHYSICAL,
	PHYSICAL_SEND_TO_PACKET_PHYSICAL,
	PHYSICAL_GET_FROM_BYTE_PHYSICAL,
	PHYSICAL_GET_FROM_PACKET_PHYSICAL
} PHYSICAL_STATE;

#endif
